
  # The bookroom api.
  bookroom_api:
    build: .
    ports:
      - "${PORT:-5001}:5001"
    volumes:
      # Mount the storage directory to the container, for storing user files.
      - ./pm2.config.js:/app/pm2.config.js:ro
      - ./uploads:/app/api/uploads
      - ./db:/app/api/db
      - ./logs:/app/logs
    env_file:
      - .env.local
    restart: unless-stopped